services:
  pikumiverse-db:
    image: postgres:15-alpine
    container_name: pikumiverse-db
    env_file:
      - .env.db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - pikumiverse-network

networks:
  pikumiverse-network:
    external: true
